name: Verify Links
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"
jobs:
  Verify:
    name: Verify links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Links
        run: |
          ./verify.sh
